/****************************************************************************
**
** Copyright (C) 2016
**
** This file is generated by the Magus toolkit
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
** "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
** LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
** A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
** OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
** LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
** DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
** THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
** (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
** OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE."
**
****************************************************************************/

#ifndef HLMS_PROPERTIES_MACROBLOCK_H
#define HLMS_PROPERTIES_MACROBLOCK_H

#include <QWidget>
#include "asset_assetwidget.h"
#include "hlms_node_macroblock.h"

QT_BEGIN_NAMESPACE

QT_END_NAMESPACE

using namespace Magus; // Use 'namespace Magus' because of issues with signal and slots;

class PropertiesDockWidget;
class HlmsPropertiesMacroblock : public QWidget
{
    Q_OBJECT

    public:
        HlmsPropertiesMacroblock(const QString& fileNameIcon,
                                 PropertiesDockWidget* propertiesDockWidget,
                                 QWidget* parent = 0);
        virtual ~HlmsPropertiesMacroblock(void);
        void setObject (HlmsNodeMacroblock* hlmsNodeMacroblock);

    private slots:
        void propertyValueChanged(QtProperty* property);
        void infoClicked(void);

    private:
        HlmsNodeMacroblock* mHlmsNodeMacroblock;
        Magus::QtAssetWidget* mAssetWidget;
        PropertiesDockWidget* mPropertiesDockWidget;
};

#endif
