/****************************************************************************
**
** Copyright (C) 2016
**
** This file is generated by the Magus toolkit
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
** "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
** LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
** A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
** OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
** LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
** DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
** THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
** (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
** OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE."
**
****************************************************************************/

#ifndef RenderwindowDOCWIDGET_H
#define RenderwindowDOCWIDGET_H

#include <QtWidgets>
#include <QMenu>
#include <QAction>
#include <QMessageBox>
#include <QToolBar>
#include <QTabWidget>
#include "ogre3_renderman.h"
#include "tb_transformationwidget.h"

QT_BEGIN_NAMESPACE
class QDockWidget;
QT_END_NAMESPACE

class MainWindow;

struct MeshStruct
{
    QString meshName;
    QVector3D scale;
};

/****************************************************************************
 This class represents a DockWidget
 ***************************************************************************/
class RenderwindowDockWidget : public QDockWidget
{
	Q_OBJECT

	public:
		RenderwindowDockWidget(QString title, MainWindow* parent, Qt::WindowFlags flags = 0);
		~RenderwindowDockWidget(void);
		void createActions(void);
		void createMenus(void);
		void createToolBars(void);
        void updateTransformationWidgetFromOgreWidget(void);
        void addToMeshMap(const QString name,
                          const QString meshName,
                          QVector3D scale);

	private slots:
        void doChangeItemAction(QAction* action);
        void doTransformationWidgetValueChanged(void);
        void doChangeBackgroundAction(void);

    protected:
        void preLoadMeshMap(void);

	private:
		MainWindow* mParent;
        QMainWindow* mInnerMain;
        Magus::QOgreWidget* mOgreWidget;
        QAction* mChangeBackgroundAction;
        QToolBar* mHToolBar;
        QMap<QString, MeshStruct> mMeshMap;
        Magus::TransformationWidget* mTransformationWidget;
        QMenu* mMeshMenu;
};

#endif

