/****************************************************************************
**
** Copyright (C) 2016
**
** This file is generated by the Magus toolkit
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
** "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
** LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
** A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
** OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
** LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
** DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
** THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
** (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
** OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE."
**
****************************************************************************/

#ifndef MAGUS_PROPERTY_WIDGET_CURVE_H
#define MAGUS_PROPERTY_WIDGET_CURVE_H

#include <QWidget>
#include <QLabel>
#include <QPixmap>
#include <QPushButton>
#include "asset_curve_dialog.h"
#include "asset_propertywidget.h"
#include "asset_curve_dialog.h"

QT_BEGIN_NAMESPACE

QT_END_NAMESPACE

namespace Magus
{
    /****************************************************************************
    Property class for curves
    ***************************************************************************/
    class QtCurveProperty : public QtProperty
    {
        Q_OBJECT

        public:
            QtCurveProperty(const QString& title, QWidget* parent = 0);
            virtual ~QtCurveProperty(void) {}
            void setIconDir(const QString& iconDir); // Also sets the static image
            void setCurveSize(const QSize& size);

        private slots:
            void propertyValueChanged(void);
            void dialogButtonClicked(void);

        private:
            QString mIconDir;
            QtCurveDialog* mCurveDialog;
            QLabel* mCurveLabel;
            QPixmap mCurvePixmap;
            QSize mCurveSize;
            QPushButton* mDialogButton;
    };
}

#endif
